In [1]:
import tensorflow as tf


In [2]:
text_ds=tf.data.Dataset.list_files('Reviews/*/*',shuffle=False)

In [3]:
text_ds

<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>

In [4]:
len(text_ds)

4

In [5]:
type(text_ds)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [7]:
for file in text_ds.take(2):
    print(file.numpy())

b'Reviews\\Negative\\Neg1.txt'
b'Reviews\\Negative\\Neg2.txt'


In [10]:
text_ds=text_ds.shuffle(1)
for file in text_ds.take(2):
    print(file.numpy())

b'Reviews\\Negative\\Neg1.txt'
b'Reviews\\Negative\\Neg2.txt'


In [12]:
def get_label(file_path):
    import os
    parts=tf.strings.split(file_path,os.path.sep)
    return parts[-2]

In [13]:
get_label('Reviews\\Negative\\Neg1.txt')

<tf.Tensor: shape=(), dtype=string, numpy=b'Negative'>

In [16]:
def process(file_path):
    path=get_label(file_path)
    new=tf.io.read_file(file_path)
    return new,path

In [18]:
img,label=process("Reviews\\Negative\\Neg1.txt")

In [19]:
img,label

(<tf.Tensor: shape=(), dtype=string, numpy=b"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them.">,
 <tf.Tensor: shape=(), dtype=string, numpy=b'Negative'>)

In [20]:
review_ds_label=text_ds.map(get_label)

In [24]:
review_ds_label

<MapDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>